### ISSUE TITLE
Cannot run with AWS adapter: "Source must not be null"

### ISSUE THREAD

**Issue by craigmccarter** [spring-cloud/spring-cloud-function#113]
I'm attempting to run a lambda (practically identical to the [adapter sample](https://github.com/markfisher/spring-cloud-function-adapters/tree/master/spring-cloud-function-adapter-sample)), but having difficulty when it tries to run the SpringApplication.

What I am seeing is as follows:

```
21:26:56.384 [main] INFO lambdainternal.LambdaRTEntry - No active profile set, falling back to default profiles: default
21:26:56.384 [main] DEBUG org.springframework.boot.SpringApplication - Loading source null
21:26:56.406 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalArgumentException: Source must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:133)
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
	at org.springframework.boot.SpringApplication.load(SpringApplication.java:635)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:355)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer.initialize(SpringFunctionInitializer.java:90)
	at org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.handleRequest(SpringBootStreamHandler.java:54)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:281)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
```

I've not dug into the guts of Spring much, but below is my interpretation of what I see happening:

As I look at the SpringFunctionInitializer, it strikes me odd that at line 88 it creates a new SpringApplicationBuilder: `new SpringApplicationBuilder(configurationClass);`.
This sets the sources with my main class, yet when it performs `builder.web(false).run()` on line 90, that call appears to set sources to null again (since no sources were passed to `run()`).
See SpringApplicationBuilder line 134: `this.context = build().run(args);`. At this point, as far as I can tell by tracing, args is null, and this will overwrite the sources passed to the SpringApplicationBuilder constructor?

I've no doubt I've made some incorrect assumptions along the way...

**Comment by nkatkamwar** [comment]
@craigmccarter if you are just trying to get something running on aws, try this resource
https://dzone.com/articles/run-code-with-spring-cloud-function-on-aws-lambda

**Comment by edeandrea** [comment]
I'm having the same issue as described by @craigmccarter . I also took the code exactly from the article referenced by @nkatkamwar and tried to deploy that but it doesn't work either, although I get a different error:

```javascript
{
  "errorMessage": "2017-10-16T18:12:25.852Z 89b1317e-b29d-11e7-b092-7926702960d0 Task timed out after 10.00 seconds"
}
```

```
10/16/2017 14:12:15 EDT	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10/16/2017 14:12:15 EDT	SLF4J: Defaulting to no-operation (NOP) logger implementation
10/16/2017 14:12:15 EDT	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10/16/2017 14:12:15 EDT	START RequestId: 89b1317e-b29d-11e7-b092-7926702960d0 Version: $LATEST
10/16/2017 14:12:17 EDT	 .   ____          _            __ _ _
10/16/2017 14:12:17 EDT	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
10/16/2017 14:12:17 EDT	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
10/16/2017 14:12:17 EDT	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
10/16/2017 14:12:17 EDT	  '  |____| .__|_| |_|_| |_\__, | / / / /
10/16/2017 14:12:17 EDT	 =========|_|==============|___/=/_/_/_/
10/16/2017 14:12:17 EDT	 :: Spring Boot ::                        
10/16/2017 14:12:18 EDT	
10/16/2017 14:12:25 EDT	END RequestId: 89b1317e-b29d-11e7-b092-7926702960d0
10/16/2017 14:12:25 EDT	REPORT RequestId: 89b1317e-b29d-11e7-b092-7926702960d0	Duration: 10004.82 ms	Billed Duration: 10000 ms 	Memory Size: 512 MB	Max Memory Used: 91 MB	
10/16/2017 14:12:25 EDT	2017-10-16T18:12:25.852Z 89b1317e-b29d-11e7-b092-7926702960d0 Task timed out after 10.00 seconds
10/16/2017 14:12:26 EDT	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10/16/2017 14:12:26 EDT	SLF4J: Defaulting to no-operation (NOP) logger implementation
10/16/2017 14:12:26 EDT	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by edeandrea** [comment]
It has to do with the way the jar is shaded - probably something the shadow Gradle plugin isn't doing correctly. When I create a pom.xml (like https://github.com/laxika/spring-cloud-function-aws-example/blob/master/pom.xml) and run the build via Maven then upload my jar to lambda, things work just fine.

**Comment by edeandrea** [comment]
Just to add-on here - if your project builds with Gradle (not Maven) the shadow Gradle plugin doesn't merge all the spring-specific property files (i.e. spring.factories, spring.handlers, etc). You have to add some extra configuration to the shadowJar task in order to get it to work correctly:

```groovy
ext {
  mainClass = 'com.mycompany.some.package.MySpringBootMainApplicationClass'
}

shadowJar {
  classifier = 'aws'
  mergeServiceFiles()
  mergeGroovyExtensionModules()
  manifest {
    attributes(
      'Main-Class': mainClass,
      'Start-Class': mainClass,
      'Spring-Boot-Classes': ''
    )
  }
  dependencies {
    exclude dependency("org.springframework.cloud:spring-cloud-function-web:$springCloudFunctionVersion")
  }
  transform(com.github.jengelman.gradle.plugins.shadow.transformers.PropertiesFileTransformer) {
    mergeSeparator = ','
    mergeStrategy = 'append'
    paths = [
      'META-INF/spring.factories',
      'META-INF/spring.handlers',
      'META-INF/spring.provides',
      'META-INF/spring.schemas',
      'META-INF/spring.tooling',
      'META-INF/spring-autoconfigure-metadata.properties',
    ]
  }
}
```

**Comment by kennyk65** [comment]
Same error: "Source must not be null".  

Maven-built JAR.  The code in SpringFunctionInitializer.initialize had no idea what my 'main' configuration class was, so it used null.  

My work-around was to set environment variable MAIN_CLASS to com.example.demo.Application, but I didn't have to do this when I ran the https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws sample, which is largely the same.  Was I supposed to put the 'main' configuration class in a manifest somewhere?

**Comment by edeandrea** [comment]
The main configuration class (i.e. the class with `@SpringBootApplication`), like with any other Spring Boot application, should be at the root of your application's source tree. When I created a Maven pom.xml & used maven to build/shade the jar, the deployment to AWS Lambda worked fine. Gradle & the shadow plugin was a different story though - my above comment describes what I had to do to get it to work.

In either case, make sure the `META-INF/MANIFEST.MF` file that gets created in your jar has both a `Main-Class` & `Start-Class` entry where the value is the fully-qualified class name of your main application class.

**Comment by lftrevisan** [comment]
@edeandrea Thanks a lot for your suggestion of how to solve the problem on gradle. I was having a similar issue here and it worked fine. Would you mind submitting a PR with your proposal? Does anybody know if there is any intend to change spring-boot gradle plugin to automatically generate the jar on the format expected by AWS Lambda?

**Comment by edeandrea** [comment]
@lftrevisan I'm not sure what I would submit a PR to or for. In my opinion it isn't the spring-boot-gradle-plugin's job to build shaded jars. Maybe what's needed is a gradle plugin offered by the spring-cloud-function project which knows how to do what is necessary based upon my post above, since the merging of all of the `spring.*` files is something specific to Spring/Spring boot. Maybe an abstraction on top of the gradle shadow plugin which knows how to shadow Spring-specific libraries?

**Comment by lftrevisan** [comment]
I think it makes sense. The reason why I mentioned spring-boot-gradle-plugin was because I was wondering it could identify the dependency with spring-cloud-function and more specifically the aws adapter and build the aws jar. However having this as a separate plugin would also work. I think what could be done as of now is submitting a PR with the extra config for shadowJar task on https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-aws/build.gradle since the current instructions don't work for gradle.

**Comment by sebastientromp** [comment]
@craigmccarter I'm having the same issue - have you found a solution for yours?

**Comment by edeandrea** [comment]
@sebastientromp did my solution I posted above not work for you?

**Comment by sebastientromp** [comment]
I am using Maven, and as far as I could understand your case was Gradle-only, right?

**Comment by ashutoshbajpai** [comment]
@edeandrea  @craigmccarter 


Ashutosh bajpai  Shailesh Joshi 4 hours ago 
Like (0)
 
Hi ,

I downloaded the code from the below location:

https://github.com/laxika/spring-cloud-function-aws-example



After deploying the code AWS when i am passing the input then it is showing me below error:

Can anyone please help me:



Input:

{
"input": "Welcome to happy land!"
}


Please refer below Error:



Skip uploading function code since no local change is found...
Invoking function...
==================== FUNCTION OUTPUT ====================
{"errorMessage":"Source must not be null","errorType":"java.lang.IllegalArgumentException","stackTrace":["org.springframework.util.Assert.notNull(Assert.java:134)","org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:133)","org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)","org.springframework.boot.SpringApplication.load(SpringApplication.java:635)","org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:355)","org.springframework.boot.SpringApplication.run(SpringApplication.java:301)","org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)","org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer.initialize(SpringFunctionInitializer.java:91)","org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:46)"]}
==================== FUNCTION LOG OUTPUT ====================
START RequestId: e36e173c-6916-11e8-8b83-89833db52bbd Version: $LATEST

. ____ _ __ _ _
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/ ___)| |_)| | | | | || (_| | ) ) ) )
' |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot :: (v1.5.7.RELEASE)

Source must not be null: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Source must not be null
at org.springframework.util.Assert.notNull(Assert.java:134)
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:133)
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
at org.springframework.boot.SpringApplication.load(SpringApplication.java:635)
at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:355)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
at org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer.initialize(SpringFunctionInitializer.java:91)
at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:46)

END RequestId: e36e173c-6916-11e8-8b83-89833db52bbd
REPORT RequestId: e36e173c-6916-11e8-8b83-89833db52bbdDuration: 4956.74 msBilled Duration: 5000 ms Memory Size: 512 MBMax Memory Used: 97 M

**Comment by dsyer** [comment]
@ashutoshbajpai that error is the same as the OP. There's no need to repeat it. You haven't specified a main class for the app (so your MANIFEST.MF is fubar, or you haven't bothered to set it). The docs explain what you need and the sample works.

**Comment by ashubajpai** [comment]
@dsyer  i did the suggested changes( added the mainfest file ) but still i am facing this issue. Can you please tell me where i need to do exact changes?
I think you are referring the https://dzone.com/articles/run-code-with-spring-cloud-function-on-aws-lambda doc only ...and i am not sure where he mentioned this issue.

**Comment by dsyer** [comment]
I wasn't referring to that sample, but I dare say it works now if it worked then (nothing changed AFAIK). There is a sample in this project fully set up to deploy to AWS (https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws). It works, and the steps you need to deploy it are documented in the [README](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/README.adoc) for the adapter and in the user guide. Look at that sample and play spot the difference. Or publish your own code so others can try it.

**Comment by yasskant** [comment]
Seems that you try to copy properties from a nul bean. Do you have somewhere a BeanUtils.copyProperties(x,y) ? if not, possibly you are providing a null object to the library, which by the way should do the check
