### ISSUE TITLE
4.1.3 - customized objectMapper 

### ISSUE THREAD

**Issue by AlonPorter** [spring-cloud/spring-cloud-function#1165]
**Describe the bug**
After upgrading to 4.1.3 we got errors in our app regarding failing to parse some json. 
after invetigation we understad that we want to customize the object mapper to have FAIL_ON_TRAILING_TOKEN false, but can't override this value.
Hope I explain good. 
thanks in advance.

**Comment by GreenRover** [comment]
I confirm since the lates release it is not linger possible to to modify the ObjectMapper.

I would like to propose to use the object mapper created/used by spring boot instead of creating an dedicated one that can not be modified.

My actual business problem ist:
- Dates (Instant) have to be serialized as ISO string but are currently as float Unix timestamp.
- The same objects are differently serialized when transmitted via messaging compared to an http transferred.

As ugly workaround i now de/serialize everything outside of spring cloud stream, what means dont be able to use a key feature of spring cloud function.

In my opinion such changes are a no go for a minion release.
@olegz  Was an intended change or can we consider this as a bug?

**Comment by olegz** [comment]
I believe this has been addressed - https://github.com/spring-cloud/spring-cloud-function/issues/1148
You can go back to configuring ObjectMapper the standard way.
Please file a new issue if the problem persists
