### ISSUE TITLE
Specify active profile for deployed cloud function on AWS Lambda

### ISSUE THREAD

**Issue by mengjiann** [spring-cloud/spring-cloud-function#135]
Is it possible to specify active profile for deployed cloud function on AWS Lambda using environment variables?

For normal Spring boot application, I will need to add different profiles under the spring-boot-maven-plugin configuration.  But how about cloud function for running on AWS lambda?

Thanks.

**Comment by trisberg** [comment]
You can set the active profiles with an env var like `SPRING_PROFILES_ACTIVE=myprofile`

**Comment by mengjiann** [comment]
I have been using application-{profile}.properties for my other spring boot projects. Then, I just discovered that I can specify the spring.profiles.active under application.properties.

`spring.profiles.active=${SPRING_PROFILES_ACTIVE:<default value>}`

Thus, it works. Thanks!

**Comment by vany0114** [comment]
Guys @mengjiann @trisberg, I'm new on Java, Spring boot and Lambda, so I'm kida confused how can I achive that once I deployed my funcions on different environments. Right now I have two different profiles: `application-sandbox.properties` and `application-prod.properties`. 

Also I added this to both files:
`spring.profiles.active=${SPRING_PROFILES_ACTIVE:sandbox}`

And my hadler looks like this:
`handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class, "prod", "sandbox");`

So, is it supposed that in the `Environment variables` section of the lambda I have to set the `SPRING_PROFILES_ACTIVE`  variable with `sandbox`/`prod` respectively?

Really appreciate your help guys in advance.

**Comment by vany0114** [comment]
Also, when I try to install `spring-boot-maven-plugin` I got this error:

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.2.RELEASE:repackage (repackage) on project myProject: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.2.2.RELEASE:repackage failed: Source must refer to an existing file, got D:\Repos\myProject\target\classes
```

**Comment by vany0114** [comment]
Well, it seems it was because of the versio of `aws-serverless-java-container-springboot`, I created the project some months ago using `mvn archetype:generate`  but today I tryed generating the project again and I noticed that several things are different now. 

* Version of `spring-boot-starter-parent` (2.1.8.RELEASE now)
* It uses `aws-serverless-java-container-springboot2` instead of `aws-serverless-java-container-springboot`
* Exclusion of `spring-boot-starter-tomcat` on `spring-boot-starter-web`
* Application class is now simpler, doesn't hinretince from `SpringBootServletInitializer`

After those changes, spring profiles are working as expected.
