### ISSUE TITLE
Azure's function.json should be generated

### ISSUE THREAD

**Issue by Clockwork-Muse** [spring-cloud/spring-cloud-function#146]
(this appears to be known from comments in another issue, but there's no tracking at the moment)

Azure uses a set of annotations to generate the relevant `function.json`s (since there may be more than one function).  This appears to be done via a maven plugin - it may be possible to reuse this.

**Comment by dsyer** [comment]
The problem is that the Azure Java programming model kind of goes against the grain of Spring Cloud Function (functions are supposed to be pure business and not aware of the source of the events that are driving them). I think it's OK for a build-time step to express those concerns ("here's my code, please hook it up to an HTTP gateway", for example), but I don't like having them in the source code really. I certainly don't like the idea of writing those JSON files myself, so we'll need some tools. I just don't know if the current Azure model is a good fit.

The Azure team at Microsoft have expressed some interest in working together on this a bit so there might be some changes in the pipeline. Any ideas you (or anyone else) has would be more than welcome.

**Comment by dsyer** [comment]
The maven plugin is the best way to do this and the docs and samples show how. Gradle support would have to come from Microsoft.
