### ISSUE TITLE
Migrate adapters to Gson

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#151]
It's much faster on startup, so we should use that if it's available.

**Comment by olegz** [comment]
Do we still need to do that @dsyer given that we now operate at JsonMapper level, so Gson or Jackson is irrelevant in this context?
Or perhaps change this issue to make Gson default?

**Comment by olegz** [comment]
Well, Google adapter uses Gson. I can try to throw an example into AWS as well

**Comment by olegz** [comment]
I am going to close it since we actually support both (at the FunctionInvocationWrapper and MessageConverters level) via [JsonMapper](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/json/JsonMapper.java)  for which we provide two implementations (Jackson and Gson) and user can chose/configure what they want to use. And it is now [documented](https://github.com/spring-cloud/spring-cloud-function/issues/677).
