### ISSUE TITLE
Support production of events from a bean of type `Flux<T>`

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-function#162]
please support production of tems from a bean of type `Flux<T>`

**Comment by dsyer** [comment]
I guess this is a synonym for `Supplier<Flux<T>>`?

**Comment by dsyer** [comment]
I'd be concerned about the subscription semantics. How many subscribers are allowed, or expected? How can the user control it?

**Comment by olegz** [comment]
@joshlong Unless I am out of context with the recently announced release of [SCSt 2.0.0.M2](https://spring.io/blog/2018/08/28/spring-cloud-stream-fishtown-m2-2-1-0-m2-release-announcement) you can do this:
```
@SpringBootApplication
@EnableBinding(Source.class)
public class MyFunctionBootApp {

	public static void main(String[] args) {
		SpringApplication.run(MyFunctionBootApp.class, 
                  "--spring.cloud.stream.function.definition=date");
	}

	@Bean
	public Supplier<Date> date() {
		return () -> new Date();
	}
}
```
The signature of the Supplier can be `Flux<T>` if you wish. It's entirely user's choice since all functions converted to flux functions anyway if they are not already are.

The above will also rely on default poller configuration or you can provide your own

So I am closing it, but feel free to reopen if I am out of context.
