### ISSUE TITLE
Spring Integration support not working in 2.0.0.M3

### ISSUE THREAD

**Issue by krmeda** [spring-cloud/spring-cloud-function#211]
I am trying to execute same example code as https://github.com/artembilan/spring-integration-s1p2017/blob/master/src/main/java/org/springoneplatform2017/integration/function/SpringIntegrationS1p2017Function.java in a gradle project. Spring Function is not utilizing the bean generated by Spring Integration with version `2.0.0.M3`.

The example works as expected when using `1.0.0.RELEASE` version of Spring Cloud Function. 

This is the `build.gradle` I am using to replicate the problem:
```
buildscript {
	repositories {
		mavenCentral()
	}
}

plugins {
	id 'java'
	id 'io.franzbecker.gradle-lombok' version '1.14'
	id "io.spring.dependency-management" version "1.0.5.RELEASE"
	id "org.springframework.boot" version "2.0.5.RELEASE"
}

group = 'com.sample.test.scf'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
}


ext {
	springCloudVersion = 'Finchley.SR1'
}

dependencies {
	implementation('org.springframework.boot:spring-boot-starter-actuator')
	implementation('org.springframework.cloud:spring-cloud-function-web:2.0.0.M3')
	implementation('org.springframework.cloud:spring-cloud-function-core:2.0.0.M3')
    implementation('org.springframework.cloud:spring-cloud-function-deployer:2.0.0.M3')
//	implementation('org.springframework.cloud:spring-cloud-starter-function-web')
	implementation('org.springframework.boot:spring-boot-starter-integration')
	implementation('org.springframework.boot:spring-boot-starter-webflux')
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	testImplementation('io.projectreactor:reactor-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```

This is the `@Bean` declaration in my Spring Boot Application is:
```    @Bean
    public IntegrationFlow uppercaseSiFlow() {
        return IntegrationFlows.from(MessageFunction.class, "uppercase")
                .<String,String>transform(String::toUpperCase)
                .log(LoggingHandler.Level.WARN)
                .bridge()
                .get();
}
```

**Comment by artembilan** [comment]
There is the code in the `ContextFunctionCatalogInitializer`: 
```
	@Override
		public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry)
				throws BeansException {
...

	if (context.getBeanFactory().getBeanNamesForType(FunctionCatalog.class, false,
					false).length == 0) {
				context.registerBean(InMemoryFunctionCatalog.class,
						() -> new InMemoryFunctionCatalog());
				context.registerBean(FunctionRegistrationPostProcessor.class,
						() -> new FunctionRegistrationPostProcessor(
								context.getBean(FunctionRegistry.class)));
			}
}
```

First of all we don't wait here for the `ContextFunctionCatalogAutoConfiguration` to be processed, therefore we register a `InMemoryFunctionCatalog` and then we end up with the : 

```
   ContextFunctionCatalogAutoConfiguration:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.cloud.function.context.FunctionCatalog; SearchStrategy: all) found beans of type 'org.springframework.cloud.function.context.FunctionCatalog' org.springframework.cloud.function.context.catalog.InMemoryFunctionCatalog (OnBeanCondition)
```

This is how that `InMemoryFunctionCatalog` overrides potential way to get all the `Function` beans from the application context in the `ContextFunctionCatalogAutoConfiguration` and we rely in our app only on the `FunctionRegistration` - I assume manual registration.

Second any `BeanPostProcessor` should not be with autowiring. That's going to cause some problems during early initialization, e.g. missed `Function` bean registered by Spring Integration, for example.
I'm, talking about that `context.getBean(FunctionRegistry.class)`. If we need that in the logic, it would be better to perform it lazily.

I don't know what is the purpose to always override a  `ContextFunctionCatalogAutoConfiguration` with the `InMemoryFunctionCatalog`, but this looks like the root of our problems.

We to schedule some discussion, @olegz .

**Comment by olegz** [comment]
@artembilan Recently we had similar lifecycle issue with Kotlin lambdas. (see https://github.com/spring-cloud/spring-cloud-function/issues/224 from @ilayaperumalg). It was fixed by moving post processing logic of Kotlin lambdas from BPP to BFPP (see https://github.com/spring-cloud/spring-cloud-function/commit/8eb7e06e02d5e5118ac60a5416ada6fb73b34aba). Perhaps the approach could be reused to address this specific issue with SI?

**Comment by artembilan** [comment]
That's fully not similar and there is no way to fix it the same style in Spring Integration. 
See my comment here: https://github.com/spring-cloud/spring-cloud-function/issues/227#issuecomment-434745740.

The problem with Spring Integration that there is a lot dependency injections from other services to be used in the `IntegrationFlow`, therefore we can't parse Java DSL so early in the `BFPP`.
You are welcome to come there and check if we can do anything on the matter, but believe me that we started from the `BFPP` in the beginning of Java DSL development and we failed because of dependency injection.

Another my point for this kind of issues that you are missing the fact that beans can be added at runtime and I don't talk here already about Spring Integration, although we recently did there a lot of work to meet runtime bean registration requirements, including HTTP and WebFlux endpoints mapping and also MBeans registration in JMX. So, maybe you can re-think the current `@Autowired` solution in favor of some `BPP` logic to track appropriate function beans whenever they appear in the application context...

I'm also open for the call if you feel we need to discussion anything else.

Thanks for understanding!

**Comment by olegz** [comment]
I think this has been resolved already and Artem pushed an updated sample.

I'll close it, but feel free to re-open it or raise a new one if you still think there is an issue
