### ISSUE TITLE
Kotlin lambdas fail to register as functions in FunctionRegistry

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#227]
Depending on the style of configuration there are chances that BeanFactoryFunctionCatalog is created before Kotlin lambdas get transformed, thus missing all together.
This is due to the fact that their transformation into java Functions is done via BPP.

Consider moving the transformation logic to BFPP.

**Comment by ilayaperumalg** [comment]
This is similar to https://github.com/spring-cloud/spring-cloud-function/issues/224

**Comment by artembilan** [comment]
I would say that we have the same problem here: #211 

The real issue that `ContextFunctionCatalogAutoConfiguration` uses regular beans injection:
```
	@Autowired(required = false)
	private Map<String, Supplier<?>> suppliers = Collections.emptyMap();

	@Autowired(required = false)
	private Map<String, Function<?, ?>> functions = Collections.emptyMap();

	@Autowired(required = false)
	private Map<String, Consumer<?>> consumers = Collections.emptyMap();

	@Autowired(required = false)
	private Map<String, FunctionRegistration<?>> registrations = Collections.emptyMap();
```

Meanwhile Spring Integration `Function` bean is registered slightly later via `IntegrationFlowBeanPostProcessor` .

My idea to defer functions harvest from the application context to later phase, e.g. `SmartInitializingSingleton.afterSingletonsInstantiated()`.
Otherwise we are stuck: the Spring Integration Java DSL can't be parsed in the `BFPP`...

Thanks for understanding
