### ISSUE TITLE
FunctionScan breaks SpringBootApplication

### ISSUE THREAD

**Issue by filiphr** [spring-cloud/spring-cloud-function#232]
Not sure if this is a bug or not. However, I think that it requires some clarifications in the samples or the Javadoc of `FunctionScan`. I was trying it out and I got hit by my extra configuration classes not being picked up. I had the following structure.

```
com.example
    MyApplication
    MySecurityConfiguration
com.example.functions
    CharCounter
```
`MyApplication` was annotated with `@FunctionScan` and `@SpringBootApplication`. I had also spring security present. I was confused that `MyCustomSecurityConfiguration` was not initialised. After my analysis I realised that the "problem" is the fact that if there is a custom `@ComponentScan` (which `@FunctionScan` is) then that takes precedence and Spring Boot won't do its defaults. 

Looking more into this it seems like one can't even exclude auto configurations, as the `@ComponentScan` by `@SpringBootApplication` would be ignored (I have not tested this, just an assumption).

**Comment by olegz** [comment]
@filiphr Perhaps we need to document it a bit more, but annotating a class with `@SpringBootApplication` and `@FunctionScan` is effectively the same as annotating it twice with `@ComponentScan` since both are.  What I am saying is that if it's already a `@SpringBootApplication`, then simply rely on its attributes to direct scanning, exclusions etc.

**Comment by filiphr** [comment]
Agreed that it should be documented a bit. Once I realised that `@FunctionScan` is just another `@ComponentScan` then it was clear to me.

>What I am saying is that if it's already a `@SpringBootApplication`, then simply rely on its attributes to direct scanning, exclusions etc.

`@FunctionScan` has a different `@ComponentScan` then `@SpringBootApplication`. If one doesn't use `@FunctionScan` than functions need to be made `@Component`(s), if `@FunctionScan` is used then your function should only implement a `java.util.function.Function`. I know that you are aware about this, just putting it out there

**Comment by olegz** [comment]
@filiphr Actually after discussing it internally we decided to remove it all together. 
We actually never publicly documented it so interesting how you got around to it

Anyway, ever since we included it in auto-configuration (see `ContextFunctionCatalogAutoConfiguration`) it became of no value to the end user. All it did is provide additional scanning instructions and established a default one. 

- So the default one remains the same `functions`
- You can still override it with `spring.cloud.function.scan.packages` property
- I've also added support for scanning for `Suppliers` and `Consumers.`

**Comment by filiphr** [comment]
Thanks for clearing this out @olegz.

I agree with your approach and it is better for the end user.
>We actually never publicly documented it so interesting how you got around to it

I was looking at the example apps and they had it 😄. I was also a bit confused why I couldn't find it in the docs.
