### ISSUE TITLE
BeanFactoryFunctionCatalog doesn't get initialized when using spring.main.lazy-initialization=true

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#381]
The callback is a `SmartInitializingSingleton` so if it doesn't get initialized, it never gets called. We can probably rejig it so that it works in the lazy bean case as well (on the first call to `FunctionCatalog` for instance).

**Comment by olegz** [comment]
The way the new implementation of FunctionCatalog/Registry (FC/FR) is coming along we may not need to do anything here since nothing is pre-loaded/wrapped/transformed during initialisation. Functions are just beans in BF and FC/FR effectively acts as a proxy to BF when lookup and other calls are made

**Comment by dsyer** [comment]
Sounds good. I guess an integration test would be useful.

**Comment by olegz** [comment]
Actually with the tests configured with the above commit, this issue is resolved from the standpoint of spring-cloud-function. That said, it may still present an issue within the scope of the frameworks that use spring-cloud-function (e.g., spring-cloud-stream), but that would be addressed with each individual framework.
