### ISSUE TITLE
Using the Deployer at runtime?

### ISSUE THREAD

**Issue by jamesmmchugh** [spring-cloud/spring-cloud-function#446]
Is it possible to use the deployer at runtime as opposed to on startup? i.e. if I wanted to setup a framework where I can deploy/undeploy multiple functions at runtime?

A brief look at the code suggests not, but thought i'd check.

**Comment by olegz** [comment]
I am not sure why not? This [test](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-deployer/src/test/java/org/springframework/cloud/function/deployer/FunctionDeployerTests.java) effectively does that by deploying as many jars as there are test . 

I personally struggle as to what is the use case, but the answer is 'yes' regardless since deploying a function is nothing more than execution piece of java code.

Please elaborate if you can?

**Comment by olegz** [comment]
I am going to close this as it is really a question. Ini the future, please use our dedicated Stack Overflow [channel](https://stackoverflow.com/tags/spring-cloud-function) as it better benefits the greater community.

**Comment by jamesmmchugh** [comment]
FYI https://stackoverflow.com/questions/59968634/spring-cloud-function-deployer-deploy-undeploy-function-programatically-at-runti
