### ISSUE TITLE
SimpleFunctionRegistry and Proxies

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-function#514]
There are two problems in `proxyInvokerIfNecessary()`.

1. A new proxy is created to wrap an existing proxy - the advice should just be added to the existing advice chain

2. It returns the proxied target `return pf.getProxy();` instead of the `FunctionInvocationWrapper` with an updated target - causes a `ClassCastException`: https://gitter.im/spring-cloud/spring-cloud-stream?at=5eb301b322f9c45c2a72eed7

**Comment by garyrussell** [comment]
I don't get the `ClassCastException`, but the function is failed to be registered...
```java
@SpringBootApplication
@EnableRetry(proxyTargetClass = false)
public class Gitter71Application {

	public static void main(String[] args) {
		SpringApplication.run(Gitter71Application.class, args);
	}

	@Bean
	Consumer<String> consumer() {
		return new Consumer<String>() {

			@Override
			@Retryable
			public void accept(String t) {
				System.out.println(t);
			}

		};
	}

}
```

**Comment by olegz** [comment]
It turns out that `proxyInvokerIfNecessary` does not bring much value to begin with. Its idea was to ensure that user can cast POJO function to its original type, which after giving some thought is actually very wrong, since the whole point is to turn POJO Function int Function, so it can collaborate with others. So in the end removing it is al that is required.
