### ISSUE TITLE
Bean not found issue when using ExecutionContext with consumer bean of processing azure function

### ISSUE THREAD

**Issue by PoojaAggarwal01** [spring-cloud/spring-cloud-function#565]
**Describe the bug**
I have azure function created using spring cloud. I wanted to add logs so I passed ExecutionContext as a method parameter but my bean is not of Function<I,O> type. I used Consumer instead without executioncontext function is working fine but logs are not getting printed in application insights. When passing ExecutionContext as method parameter, bean not found exception is being thrown.

**Sample**

`@Bean (name = "func1")
	public Consumer<String> processorHandler (ExecutionContext context) {
context.getLogger().info("Executing Function........");
return "";
}`

**Comment by olegz** [comment]
Actually this probably needs a bit of rework since ExecutionContext is different per each invocation, so passing it as bean argument (even if it worked) would not be a good idea.

**Comment by olegz** [comment]
So this issue has been fixed as part of the recent commits https://github.com/spring-cloud/spring-cloud-function/commit/b0ef4522d48a7b29aeeb3ef9c0d3ca939bc87b5f and https://github.com/spring-cloud/spring-cloud-function/commit/3c5d905eab5e09e74e818f444c5dcf512fbc8121

The actual issue was with the way we exposed `ExecutionContext`. Basically registering it as a bean was a mistake given the Azure execution model.
Anyway, details aside there is a simpler way now to have access to the current ExecutionContext instance and that is via Message headers. So when you need access to the ExecutionContext simply declare your function signature as `Function<Message<yourpojo>, ...>` and then access ExecutionContext from message headers

```
ExecutionContext context = (ExecutionContext) message.getHeaders().get("executionContext");
```

We've actually modified Azure samples so you can see exactly how to access ExecutionContext from [this example](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-azure/src/main/java/example/Config.java#L46)
