### ISSUE TITLE
Propagate Inbound Headers to Outbound

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-function#599]
```java
	@Bean
	Function<String, String> input() {
		return str -> {
			return str.toUpperCase();
		};
	}
```

`SimpleFunctionRegistry` should propagate the inbound headers (if absent) to the outbound message, for consistency with Spring Integration.

Same thing applies to 

```java
	@Bean
	Function<Flux<String>, Flux<String>> input() {
		return flux -> flux.map(p -> p.toUpperCase());
	}
```

for the same reason, but that might be harder to fix because we no longer have a reference to the input message with reactive.

This is the root cause of https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/972 which could be fixed with a simple configuration change if the headers were propagated:

    spring.cloud.stream.kafka.bindings.input-out-0.producer.messageKeyExpression=headers['kafka_receivedMessageKey']

This works...

```java
	@StreamListener(Sink.INPUT)
	@SendTo(Source.OUTPUT)
	public String process(String in) {
		return in.toUpperCase();
	}
```

...because it is using pure Spring Integration.

**Comment by olegz** [comment]
@garyrussell Recent work on SimpleFunctionRegistry implementation effectively addressed it albeit indirectly. There are several tests in SCF that verify that and I just added one in stream - https://github.com/spring-cloud/spring-cloud-stream/commit/550931c79b4f82f89381ad313aa8a723b9838132 to verify (backported it as well). 

Also, keep in mind we can only do it for imperative functions. There is absolutely nothing we can do for reactive, since we do not have any control of the message handling since it's happening inside of flux (not inside of handler method controlled by the framework.
Basically the difference between:
```
@Bean
public Function<String, String> imperative() {
	return x -> x.toUpperCase();
}

vs.
	
@Bean
public Function<Flux<String>, Flux<String>> reactive() {
	return flux -> flux.map(x -> x.toUpperCase());
}
```
With _imperative_ the framework calls `imperative()` function on each message. With _reactive_, function is invoked only once during initialization of AC to effectively connect flux exposed by listening container to user function and the actual handling of the message is done via Flux `map()` operation. This is a well known issue which goes beyond this and applies to retries, error handling and many other things. 

So i'll resolve this one, but let me know if you still have concerns.

**Comment by olegz** [comment]
@sobychacko ^^
