### ISSUE TITLE
Passing json input to a Function with a String input type does not work as expected

### ISSUE THREAD

**Issue by ssozonoff** [spring-cloud/spring-cloud-function#694]
When defining a function with an input type String, I would expect that the input no matter what it looks like should be simply passed to the input as a String. As it is now it seems RequestProcessor tries to play smart and detects the string as Json and tries to convert it. We should at least have control over this behaviour. Maybe I m missing something ?

Referring to the code snippet below.

```
	private boolean shouldUseJsonConversion(String body, MediaType contentType) {
		return (body.startsWith("[") || body.startsWith("{"))
				&& (contentType == null || (contentType != null
						&& !"text".equalsIgnoreCase(contentType.getType())));
	}
```

I am using Hoxton.RELEASE but observed the same on previous releases.

Thanks

**Comment by olegz** [comment]
No, you're not missing anything. Indeed RequestProcessor was trying to be clever, but it has been refactored as part of https://github.com/spring-cloud/spring-cloud-function/issues/708 and `RequestProcessor` is no longer a participant. 
Unfortunately the fix is not available in Hoxton. Only in 3.1.4 (which hasn't been released yet, but soon) and up.
