### ISSUE TITLE
Json parse exceptions are swallowed

### ISSUE THREAD

**Issue by adrian-baker** [spring-cloud/spring-cloud-function#739]
`org.springframework.cloud.function.context.config.JsonMessageConverter#convertFromInternal` is implemented in a way that means Jackson deserialization exceptions are swallowed:

```java
try {
    return this.jsonMapper.fromJson(message.getPayload(), convertToType);
}
catch (Exception e) {
    if (message.getPayload() instanceof byte[] && targetClass.isAssignableFrom(String.class)) {
        return new String((byte[]) message.getPayload(), StandardCharsets.UTF_8);
    }
}
```

This means a later, much less obvious ClassCastException exception is logged when my function is invoked with the raw unparsed input:

```java.lang.ClassCastException: class [B cannot be cast to class xxxx```

Besides being an unintuitive way of communicating that the incoming JSON payload was not parseable, contextual information in the original exception is lost (Jackson itself has very fine grained error reporting, and further exceptions can be triggered in application code, for example required field validation in a constructor).

I can workaround by registering a custom converter that overrides this behaviour, but I believe the exception should be bubbled by default.

**Comment by olegz** [comment]
That is actually intentional since we go through the stack of converters and if one fails it may be that the other one will succeed, so custom converter is actually the appropriate strategy here since what this means is that non of our converters are capable of converting your input or exhibit the behavior you want and so that is one of the reasons why you would want custom converter

**Comment by adrian-baker** [comment]
So if I understand the default "out of the box" behaviour correctly:
1. First check that `JsonMessageConverter#canConvertTo` returns true, which it will if the mime type is application/json etc.
1. if so, attempt JSON parsing. If it fails, catch the exception and discard it.
1. No other converters will support the mime type or convert, so call the function anyway with the raw input, despite knowing that will result in a `ClassCastException`.

That's really not ideal, especially not for the default experience, for several reasons:
- Most seriously, as described, it means that a parse error is not reported in *any* way, either back to the caller up the stack or even logged. The resulting exception is completely non-obvious, and has utterly no bearing on or hint as to the actual problem. For someone invoking the function remotely (eg an AWS Lambda), there is no way to signal that there was a problem with their request, which is why just catching and logging is a bad solution. Even when you do guess that the issue might be a deserialisation failure, the only way to learn more about it would be with a debugger.
  - As a parallel, consider something like Spring Web. It would be considered fundamentally broken if, out of the box, a POST to a handler with JSON that fails to map to Java classes would result in a ClassCastException being thrown, with no feedback on the actual parse error logged, and no way to signal this to the caller.
- It's wasteful. Even if a latter converter succeeds, relying on behaviour that attempts multiple conversions, failing some, is expensive and fragile. 
- Using exceptions as a part of a standard flow is generally an [antipattern](https://wiki.c2.com/?DontUseExceptionsForFlowControl).
- If all converters fails, it makes no sense to continue on and make a call that the framework "knows" will immediately result in a ClassCastException.

I'm trying to to think of a use case where you would want to attempt JSON parsing, let it fail with an exception, then continue onto another converter that then succeeds. Even if it does exist, I would suggest it's in the 0.1% category, in which case a custom converter should be required for the continue-on-error case, not the other way around as you're suggesting.

My suggestion would be that for the default converters present, that if
`org.springframework.cloud.function.context.config.JsonMessageConverter#canConvertTo` returns true, then any subsequent exception is bubbled up, rather than caught. For unusual scenarios where it really makes sense to attempt multiple converters, swallowing exceptions as they occur, this could still be done with a custom converter.

**Comment by olegz** [comment]
I am going to add a log statement for DEBUG

**Comment by patrickpilch** [comment]
@olegz I would like to kindly ask that you consider re-opening this ticket.

I just had my team burn a lot of time trying to understand the ClassCastException we were seeing. After having figured this out, I feel like I underwent a negative developer experience here. I think @adrian-baker 's points in https://github.com/spring-cloud/spring-cloud-function/issues/739#issuecomment-916414096 are absolutely spot-on - particularly the last bullet point. I would rather the exception raised provide assistance in understanding the root cause.

If logging is still the chosen remedy, then I believe it can be improved. The following logs seem to indicate that it's important to notify of a failure using WARN level to provide the user some breadcrumbs (line 110). But because all the logging is wrapped in `else if (logger.isDebugEnabled())`, this will never be seen at a typical INFO level. And if I have DEBUG or TRACE enabled, I'll get the log line at 107 and never 110. And the WARN log on 110 also omits the cause exception. 

If I were able to see the object mapper exception, I would have the root cause identified in all of 1 second.

https://github.com/spring-cloud/spring-cloud-function/blob/92df69206a3a84648e6dc17f773b8bb79957d449/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/JsonMessageConverter.java#L121-L133
