### ISSUE TITLE
Add initial support for BiFunction

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#884]
Such function should simply represent parsed Message.
It's signature must have `Map` as second argument to represent `MessageHeaders`

**Comment by sbernardo** [comment]
Hi @olegz , but this change:
https://github.com/spring-cloud/spring-cloud-function/blob/4c3d9d12ef20181fa80d79156a89e5213f3dd979/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/SmartCompositeMessageConverter.java#L92

broke the fix done for this issue https://github.com/spring-cloud/spring-cloud-stream/issues/2355. With this change I will receive a "null" instead of a KafkaNull instance, do you agree or I lost something in my analysis?
