### ISSUE TITLE
NPE while using spring-cloud-function-adapter-aws 3.2.6: Spring boot API running on Lambda

### ISSUE THREAD

**Issue by jhon9392** [spring-cloud/spring-cloud-function#897]
Hi Team,

Background: We were using older version on spring-cloud-function-adapter-aws with our spring boot and using SpringBootRequestHandler and it was working fine. Recently there was an vulnerability reported on a dependency package called spring cloud function context and we had to update this to latest version i.e 3.2.6

Issue: We are getting Null Pointer Exception for all @Autowired objects ever since we started with 3.2.6 version of adapter.aws and context packages. We found that SpringBootRequestHandler is deprecated and we tried other ways like RequestHandler but still @Autowired is coming as null.

**Comment by olegz** [comment]
The vulnerability you mention only really applies to a very specific case which is not AWS. IN other words it doesn't really apply to  you. Also the `SpringBootRequestHandler` is deprecated and will be removed since we used FunctionInvoker for a while now. Migrating to it is very simple and on your part will result in much less code to maintain, so consider doing that.
Also, the 3.2.x s-c-function is EOL

Anyway, I am going to close this issue and there is nothing actionable here given the explanation.
