### ISSUE TITLE
Message conversion exceptions ignored in SmartCompositeMessageConverter

### ISSUE THREAD

**Issue by radu-almasan** [spring-cloud/spring-cloud-function#901]
**Describe the bug**
Switching to `spring-cloud-dependencies:2021.0.3` `MessageConversionException` exceptions thrown by `ApplicationJsonMessageMarshallingConverter` are ignored in the `SmartCompositeMessageConverter`. Related commit: [7921842 ](https://github.com/spring-cloud/spring-cloud-function/commit/7921842943e782bf82cdcdf21627110548980537).

The unwanted side effect of this is that the handler method gets invoked with the wrong payload type, leading to class cast exceptions: 
```java
java.lang.ClassCastException: class [B cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode
```

**Sample**
```java
public Flux<...> compose(Flux<Message<ObjectNode>> flux) {
    flux.map(message -> message.getPayload().at("/foo"))
    ...
}
```

```java
@Test
void shouldRedirectJsonProcessingExceptions() {
    inputDestination.send(new GenericMessage<>("{".getBytes()), "test");

    var message = targetDestination.receive(1000, "test_errors");
    assertThat(message, is(notNullValue()));
}
```

Is this behavior expected? Is there a way to avoid this without extra steps in the handler method?

**Comment by olegz** [comment]
This is indeed expected "in a way". Let me explain.  . .
Indeed we have a stack of message converters to which user can add more message converters. When type conversion is attempted we go thru the stack attempting to find the right converter. Just because a particular converter have answered `true`  to `canConvert()` call doesn't always mean it actually can as the conversion may result in exception (your case). At that point we continue with the stack letting other converters to take a crack at it. So that is the "expected behavior" part ends. 

What I think we should do (additionally) is check the converted result after the conversion and see if it matches the actual input type. In other words in your case what must have happened is that no other converter picked it up and the result remained in raw format `byte[]`, so we should throw more intelligent exception.

That said something you can already fix by looking as to what is going on with your object and why it can not be converted and possibly implement a different message converter specific to your needs.

Meanwhile I'll look at making it a bit more intuitive

**Comment by olegz** [comment]
Actually, they are not ignored as there is a debug message. 
```
catch (Exception e) {
  if (logger.isDebugEnabled()) {
	logger.debug("Failure during type conversion by " + converter + ". Will try the next converter.", e);
  }
}
``` 
But i'll see what I can do to make it clearer

**Comment by radu-almasan** [comment]
@olegz , by just logging the exception any invalid formatted JSON coming from Kafka will get to the handler method instead of being treated as an error / exception so that the specific onError callbacks can be called on a flux.

Adding another converter won't help as even if you throw an exception from that converter it will just get caught and logged and the raw bytes will still get to the method handler causing a type error.

The only solution would be to implement checks and conversions in the actual method handler but then we lose the separation of concerns ability. I believe that's why we have converters in the first place.

For these reason I believe catching the exception and logging it is an unwanted behavior.
