### ISSUE TITLE
Spring cloud sleuth conflict with spring cloud function 3.2.6

### ISSUE THREAD

**Issue by XIAOANAndy** [spring-cloud/spring-cloud-function#905]
I meet bellow error, attached a simple project can reproduce the issue, 
spring cloud version: 2021.0.3,
spring cloud function context version: 3.2.6

**How to reproduce?**
Just start the sample application

**Issues meet when start up the application**

![image](https://user-images.githubusercontent.com/47747616/181307654-8a2b46e1-0ccd-48d9-96e2-22136788a880.png)

**Sample code**
[my-app.zip](https://github.com/spring-cloud/spring-cloud-function/files/9201257/my-app.zip)

**Comment by olegz** [comment]
Fixed. It may look like nothing but your actual issue was already fixed with the addition of support for BiFunction. So all I needed to do here is relax some of the handling of functions that are not compatible as in your case. The sleuth's instance of `FunctionAroundWrapper` is not a compatible function so it should be ignored.
